### ISSUE TITLE
dropdown overlap issue

### ISSUE THREAD

**Issue by iamrahulkumar001** [selectize/selectize-temp#1]
hello i am using selectize to make tags but the problem with that is that i am getting the selectize drop down overlapped by other div .

what i am doin is like

       <div style='width:300px;height:40px;float:left;'> // if needed i can modify this div css
       <?=functionToGetTags();?> // this is the function which is called here ...
       </div>

PHP

     function functionToGetTags(){
           <script src="tags/selectize.js"></script>
        <link rel="stylesheet" href="tags/selectize.default.css"/>
        <div class="control-group">
                 <select id="<?=$getid_i?>" multiple name="dept[]" class="demo-default" >
                     <option value=""><?=$placehol?></option>
                      <?php if ($tagwhats =='depts'){
                  // something to get ....
                  } else if($tagwhats =='skills'){
                   // something here ...
                  } ?>
                 </select>
              </div>
            <script>
                  var eventHandler = function(name) {
                return function() {
                    console.log(name, arguments);
                    $('#log').append('<div><span class="name">' + name + '</span></div>');
                };
            };
            var $select = $('#'+"<?=$getid_i?>").selectize({
                create          : true,
                onChange        : eventHandler('onChange'),
                onItemAdd       : eventHandler('onItemAdd'),
                onItemRemove    : eventHandler('onItemRemove'),
                onOptionAdd     : eventHandler('onOptionAdd'),
                onOptionRemove  : eventHandler('onOptionRemove'),
                onDropdownOpen  : eventHandler('onDropdownOpen'),
                onDropdownClose : eventHandler('onDropdownClose'),
                onFocus         : eventHandler('onFocus'),
                onBlur          : eventHandler('onBlur'),
                onInitialize    : eventHandler('onInitialize'),
                });
                </script> 
     }

Only issue is that the drop down is overlapped other things are working fine please suggest me something i have tried messing with z-index and position absolute . no help

**Comment by joallard** [comment]
Are you able to make a Codepen/JsFiddle to demonstrate the issue? It's a little hard to see what's going on exactly
